api/urls.py
from django.urls import path

from . import views

app_name = "api"
urlpatterns = [
    path("debug/", views.debug, name="debug"),
    path("debug/<int:tape_len>/<str:polarity>", views.debugSingle, name="debug_single"),
    path("test_debug", views.test_debug),
    path("get/<str:username>/<str:name>/", views.getProgram, name="get"),
    path("list/<str:username>/", views.listPrograms, name="list"),
    path("edit/<int:pk>/", views.editProgram, name="edit"),
    path("new/", views.newProgram, name="new"),
    path("delete/<int:pk>/", views.deleteProgram, name="delete"),
    path("verify/", views.verify, name="verify"),

    path("hill/", views.allHillPrograms.as_view(), name="hill_all"),
    path("hill/<str:name>/", views.getHillProgram.as_view(), name="hill"),
    path("submit/<int:pk>/", views.submitHill, name="submit"),
    path("test/<int:pk>/", views.testHill, name="test"),
    path("breakdown/<str:name>/", views.getBreakdown, name="breakdown")
]

bfjpp_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('static_apps.urls')),
    path('user/', include('users.urls')),
]

static_apps/urls.py
from django.urls import path

from . import views

app_name = "static_apps"
urlpatterns = [
    path("", views.index, name="index"),
    path("debug/", views.debug, name="debug"),
    path("rules/", views.rules, name="rules"),
    path("scores/", views.scores, name="scores"),
    path("breakdown/", views.breakdown, name="breakdown"),
    path("raw/", views.raw, name="raw"),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path("signup/", views.user_signup, name="signup"),
    path("login/", views.user_login, name="login"),
    path("signup/do/", views.do_signup, name="do_signup"),
    path("login/do/", views.do_login, name="do_login"),
    path("login/logout/", views.do_logout, name="do_logout"),
    path("<str:username>/", views.profile , name="profile"),
    path("<str:username>/program/", views.program, name="program"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <title>BF Joust++</title>

        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="{% static 'css/normalize.css' %}"/>
        <link rel="stylesheet" href="{% static 'css/skeleton.css' %}"/>
        <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
        {% block headers %}
        {% endblock headers %}
    </head>

    <body>
        <nav>
            <a class="nav-button" href="{% url 'static_apps:index' %}">Home</a>
            <a class="nav-button" href="{% url 'static_apps:debug' %}">Games</a>
            <a class="nav-button" href="{% url 'static_apps:rules' %}">Rules</a>
            <a class="nav-button" href="{% url 'static_apps:scores' %}">Scores</a>
            <a class="nav-button" href="{% url 'static_apps:breakdown' %}">Breakdown</a>
                {% if this_user %}
                    <a class="nav-button login-button" href="{% url 'users:profile' this_user %}">{{ this_user }}</a>
                    <a class="nav-button" href="{% url 'users:do_logout' %}">Logout</a>
                {% else %}
                    <a class="nav-button login-button" href="{% url 'users:login' %}">Login</a>
                    <a class="nav-button" href="{% url 'users:signup' %}">Signup</a>
                {% endif %}
        </nav>
        {% block content %}
        {% endblock content %}
    </body>
</html>

templates/breakdown.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div id="app">
        {% csrf_token %}
        <select id="program" @change="update" v-model="current_program">
            <option v-for="prog in hill_programs" v-bind:value="prog.name">[[ prog.name ]]</option>
        </select>
        <br/>

        <game v-for="game in current_games" v-bind:game="game" v-bind:main="current_program"></game>
    </div>
    <script src="https://unpkg.com/vue"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script>
        var start_prog = {% if start_prog %} "{{ start_prog }}" {% else %} "" {% endif %};
    </script>
    <script src="{% static 'js/breakdown.js' %}"></script>
{% endblock content %}

templates/debug.html
{% extends "base.html" %}
{% load static %}

{% block headers %}
    <link rel="stylesheet" href="{% static 'css/debug.css' %}">
{% endblock headers %}

{% block content %}
    <div id="app">
        {% csrf_token %}
        <h4>Left Program</h4>

        <textarea wrap="off" rows="10" v-model="left"></textarea><br/>
        <select v-model="loaded_left" @change="loadProgram(true)">
            <option v-for="prog, index in all_programs" v-bind:value="index">[[prog.name]]</option>
        </select>

        <h4>Right Program</h4>
        <textarea wrap="off" rows="10" v-model="right"></textarea><br/>
        <select v-model="loaded_right" @change="loadProgram(false)">
            <option v-for="prog, index in all_programs" v-bind:value="index">[[prog.name]]</option>
        </select>

        <br/>
        <button @click="runAlt">Run</button>
        <h2>[[ loading ]]</h2>

        <gameselect v-for="game, index in game_select"
            v-bind:game="index"
            v-bind:winner="game.winner"
            @showgame="showGame"></gameselect>

        <h2 v-show="game_select.length === 42">[[ result === 0 ? "Tie Game (0)" : (result > 0 ? `Right Wins (${result})` : `Left Wins (${result})`) ]]</h2>

        <div v-show="current_game.tape_len">Tape length [[current_game.tape_len]][[ current_game.polarity ? ", polarity inverted" : ""]]</div>

        <div v-show="current_game.tape_len">
            <canvas id="canvas" width="0" height="287"></canvas><br/>
            <button @click="playGame">[[ is_playing ? "■" : "▶" ]]</button>
            <input type="range" id="play_slider" min="0" max="100" value="0">
        </div>

        {% comment %} <div v-show="showTextDisplay" class="turn-container">
            <turn v-for="(turn, index) in current_game.turns"
                v-bind:turn="turn"
                v-bind:turn_num="index"
                v-bind:tape="current_tape[index]"></turn>
        </div> {% endcomment %}
        <div class="turn-container" v-html="text_out"></div>
    </div>


    <script src="https://unpkg.com/vue"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script>
        var got_left_prog = {% if left %} `{{ left }}` {% else %} "" {% endif %};
        var got_right_prog = {% if right %} `{{ right }}` {% else %} "" {% endif %};
        var got_tleft_prog = {% if tleft %} `{{ tleft }}` {% else %} "" {% endif %};
        var got_tright_prog = {% if tright %} `{{ tright }}` {% else %} "" {% endif %};
        var current_user = {% if this_user %} `{{ this_user }}` {% else %} "" {% endif %};
    </script>
    <script src="{% static 'js/debug.js' %}"></script>

{% endblock content %}

templates/index.html
{% extends "base.html" %}

{% block content %}
    <div id="app">
        <h1>BF Joust++ Hill</h1>
        <p>Welcome to the BF Joust++ Hill!</p>
        <p><strong>{{ top_hill.name }}</strong> is on the top of the hill, out of {{ num_hill }} programs.</p>
        <p>Click
        <a href="{% url 'static_apps:debug' %}?tleft={{ random_left.name }}&tright={{ random_right.name }}">
        here</a> to see a random game.</p>
    </div>
{% endblock content %}

templates/login.html
{% extends "base.html" %}

{% block content %}
    <div id="app">
        <h2>{{ error }}</h2>
        
        <form action="{% url 'users:do_login' %}" method="post" class="login-form">
            {% csrf_token %}

            <label for="username">Username: </label>
            <input type="text" id="username" name="username" required/>

            <br/>

            <label for="password">Password: </label>
            <input type="password" id="password" name="password" required/>

            <br/>

            <input type="submit" value="Log in" />
        </form>
    </div>
{% endblock content %}

templates/profile.html
{% extends "base.html" %}

{% block content %}
    <div id="app">
        <h2>{{ profile.username }}</h2>

        {% if is_current %}
            <a class="button" href="{% url 'users:program' this_user %}">New</a>
        {% endif %}

        <div class="row" style="border-bottom: 1px solid lightgray; margin-bottom: 16px;">
            <div class="four columns"><h5>Name</h5></div>
            <div class="two columns"><h5>Updated</h5></div>
            <div class="six columns"><h5>Options</h5></div>
        </div>

        {% for program in programs %}
            <div class="row">
                <div class="four columns"><strong>{{ program.name }}</strong></div>
                <div class="two columns">{{ program.updated }}</div>
                <div class="six columns">
                    {% if is_current %}
                        <a href="{% url 'users:program' profile.username %}?name={{ program.name }}"><button>Edit</button></a>
                    {% endif %}
                    <a href="{% url 'static_apps:debug' %}?left={{ profile.username }}.{{ program.name }}"><button>Play</button></a>
                    <a href="{% url 'static_apps:raw' %}?author={{program.author}}&name={{program.name}}"><button>Raw</button></a>
                </div>
            </div>
        {% empty %}
            <p>This user has no programs to show</p>
        {% endfor %}
    </div>
{% endblock content %}

templates/program.html
{% extends "base.html" %}
{% load static %}

{% block headers %}
    <style>
        textarea {
            width: 100%;
            height: 512px;
            font-family: monospace;
        }
        .private-label {
            margin-left: 10%;
        }
    </style>
{% endblock headers %}

{% block content %}
    <div id="app">
        {% csrf_token %}
        <button @click="save">Save</button>
        <button @click="remove">Delete</button>
        <button @click="verify">Verify</button>
        <button @click="play">Play</button>
        <button @click="test">Test</button>
        <button @click="submit">Submit</button>

        <br/>
        <h3 style="white-space: pre-wrap;">[[ err_msg ]]</h3>
        
        <input type="text" v-model="name"/>
        <span class="private-label">Private</span>
        <input type="checkbox" v-model="private"/>

        <br/>

        <textarea rows="40" v-model="content"></textarea>

    </div>

    <script src="https://unpkg.com/vue"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script>
        const current_author = "{{ author }}";
        {% if is_new %}
            var is_new_program = true;
        {% else %}
            var is_new_program = false;
            var load_name = "{{ name }}";
        {% endif %}
    </script>
    <script src="{% static 'js/edit.js' %}"></script>
{% endblock content %}

templates/raw.html
{% extends "base.html" %}
{% load temptags %}
{% load static %}

{% block headers %}
    <link rel="stylesheet" href="{% static 'css/raw.css' %}" />
{% endblock headers %}

{% block content %}
    <div class="rawhead row">
        <div class="four columns"><h4>{{ prog_name }}</h4></div>
        <div class="two columns">
            <a href="{% url 'users:profile' author  %}"><h5>{{ author }}</h5></a>
        </div>
        <div class="two columns"><a class="button" href="{% url 'static_apps:raw'%}?{% if on_hill %}hill={{ prog_name }}{% else %}author={{ author }}&name={{ prog_name }}{% endif %}&plaintext=true">Plaintext</a></div>
    </div>
    <div class="rawpage">
        {% for line in raw %}
            <div class="line" id="{{ forloop.counter }}"><span class="linenum">{{ forloop.counter|numspace:max_digits }}</span><div>{{ line }}</div></div>
        {% endfor %}
    </div>
{% endblock content %}

templates/rawtext.html
<!DOCTYPE html>

<html>
    <head>
        <title>BF Joust++</title>
    </head>
    <body>
        <pre style="font-family: monospace;">{{ program }}</pre>
    </body>
</html>

templates/rules.html
{% extends "base.html" %}

{% block content %}
{% comment %}
    {% def funcname arg1 ... :: const1_id const1_value ... %}
    {% enddef %}

    {% call funcname param1 ... %}
    
{% endcomment %}
<div id="app">
    <p>BF Joust++ is based on <a href="https://esolangs.org/wiki/BF_Joust">BF Joust</a>. Any BF Joust program will work
    in BF Joust++.</p>
    <h3>The Tape</h3><hr/>
    <p>
        Each match takes place on a tape 12 to 32 cells long.
        The first (and last) cell is the <em>register</em>.
        The second (and second to last) cell is the <em>flag</em>.
        Each cell can hold a value from 0 to 255, which wraps around.
        All cells start with a value of zero at the beginning of the match, except for the flags, which start at 128.
    </p>
    <h3>The Game</h3><hr/>
    <p>
        At the start of each match, the programs start on their flag. A program loses when:
        <ul>
            <li>That program's flag has a value of zero for two conescutive turns, or</li>
            <li>The program moves outside the bounds of the tape
            (<code>&lt;</code> on their register or <code>&gt;</code> on the opponent's register)</li>
        </ul>
        Each game consists of 42 matches: 21 matches on tape lengths 12 to 32, and 21 matches on those same tape length's
        with polarity inversed. Inversed polarity means that for one of the programs, <code>+</code> is switched with
        <code>-</code> and <code>#</code> is switched with <code>~</code>.
    </p>
    <h3>Instructions</h3><hr/>
    <p>
        <div class="row">
            <div class="one column"><code>&gt;</code></div>
            <div class="ten columns">move pointer towards opponent</div>
        </div>
        <div class="row">
            <div class="one column"><code>&lt;</code></div>
            <div class="ten columns">move pointer away from opponent</div>
        </div>
        <div class="row">
            <div class="one column"><code>+</code></div>
            <div class="ten columns">increase tape element by one (polarity dependant)</div>
        </div>
        <div class="row">
            <div class="one column"><code>-</code></div>
            <div class="ten columns">decrease tape element by one (polarity dependant)</div>
        </div>
        <div class="row">
            <div class="one column"><code>.</code></div>
            <div class="ten columns">do nothing</div>
        </div>
        <div class="row">
            <div class="one column"><code>,</code></div>
            <div class="ten columns">write current tape element to register</div>
        </div>
        <div class="row">
            <div class="one column"><code>#</code></div>
            <div class="ten columns">increase register by one (polarity dependant)</div>
        </div>
        <div class="row">
            <div class="one column"><code>~</code></div>
            <div class="ten columns">decrease register by one (polarity dependant)</div>
        </div>
        <div class="row">
            <div class="one column"><code>?</code></div>
            <div class="ten columns">set condition to (tape != 0)</div>
        </div>
        <div class="row">
            <div class="one column"><code>=</code></div>
            <div class="ten columns">set condition to (tape == register)</div>
        </div>
        <div class="row">
            <div class="one column"><code>!</code></div>
            <div class="ten columns">set condition to (tape != register)</div>
        </div>
        <div class="row">
            <div class="one column"><code>&amp;</code></div>
            <div class="ten columns">set condition to (register != 0)</div>
        </div>
        <div class="row">
            <div class="one column"><code>[</code></div>
            <div class="ten columns">goto matching ] if condition is false</div>
        </div>
        <div class="row">
            <div class="one column"><code>]</code></div>
            <div class="ten columns">goto matching [ if condition is true</div>
        </div>
        <div class="row">
            <div class="one column"><code>:</code></div>
            <div class="ten columns">if condition is false, jump to matching | (or ; if there is no |)</div>
        </div>
        <div class="row">
            <div class="one column"><code>|</code></div>
            <div class="ten columns">goto matching ; (this is an else statement)</div>
        </div>
        <div class="row">
            <div class="one column"><code>;</code></div>
            <div class="ten columns">do nothing (this is the endif)</div>
        </div>
    </p>
    <h3>Preprocessing</h3><hr/>
    <p>
        BF Joust++ has some commands that make code shorter, easier to read, and easier to make. These commands aren't instructions;
        they do not use a step to execute. They also do not fundamentally change the game: theoretically speaking, if one had
        infinite time and memory, <strong>there is nothing these commands could do that couldn't be programmed manually.</strong>
    </p>
    <h4>Comments</h4>
    <p>
        Anything between <code>{*</code> and <code>*}</code> is ignored and will not be executed.
    </p>
    <h4>Basic Loop</h4>
    <p>
        Repeating code can be expressed with <code>(CODE)*LOOPS</code>. If LOOPS has a negative value, it will repeat forever.
        As an example, <code>(+-)*5</code> is equivilent to <code>+-+-+-+-+-</code>.
    </p>
    <h4>Nested Loop</h4>
    <p>
        Repeating code that would contain any unmatched <code>[</code> <code>]</code> <code>:</code> <code>|</code>
        or <code>;</code>. This can be expressed as <code>(A{B}C)%LOOPS</code>. As an example, <code>([-{.}]>)%4</code>
        is equivilent to <code>[-[-[-[-.]>]>]>]></code>.
    </p>
    <h4>Values</h4>
    <p>
        For Basic Loops and Nested Loops, plain numbers were used in the examples. However, variables and even expressions
        can be used instead. Using variables is simple: instead of a number (<code>(.)*5</code>), use the variable name
        (<code>(.)*var</code>). For expressions, simply put the expression between <code>{&#37;</code> and <code>&#37;}</code>.
        As an example, <code>(.)*{&#37;5 + 7 - 2&#37;}</code> is equivilent to <code>(.)*10</code>. <!--TODO: List operations-->
    </p>
    <h4>Blocks</h4>
    <p>
        Blocks are a way to declare variables in certain parts of code. They are expressed as:<br/>
        <code>{&#37; block VAR_NAME VAR_VALUE ... &#37;} CODE {&#37; endblock &#37;}</code><br/>
        All code inside the block will have access to all variables declared by the block. For VAR_VALUE, the same way of
        using values described above still holds, except expressions must be inside () instead of {&#37;&#37;}. Multiple variables
        can be declared by a block.
    </p>
    <h4>For Loop</h4>
    <p>
        For loops act much the same way they do in most other programming languages. They are expressed as:<br/>
        <code>{&#37; for NAME INI END STEP :: NAME1 INI1 STEP1 ... &#37;} CODE {&#37; endfor &#37;}</code><br/>
        where NAME is the name of the loop variable, INI is the initial value of the loop variable, END is the value that
        when reached or surpassed ends the loop, and STEP is how to change the loop variable every loop.
        In essence, it behaves like:<br/>
        <code>for(int NAME = INI; NAME < END; NAME += STEP){CODE}</code><br/>
        The <code>::</code> and eveything after it is optional; they specify other variables that change with the loop, but
        don't affect when it stops. There can be any number of these extra variables as long as they all have a name, ini, and step,
        in that order. If there are no extra variables specified, do not include the <code>::</code>.<br/>
        It should also be noted that if STEP is negative, the loop will instead continue while <code>NAME > END</code>.
    </p>
    <h4>If Statements</h4>
    <p>
        If statements act much the same way they do in most other programming languages. They can be expressed as:<br/>
        <code>{&#37; if VALUEA &#37;} CODEA {&#37; elif VALUEB &#37;} CODEB {&#37; else &#37;} CODEC {&#37; endif &#37;}</code><br/>
        The elif and else are optional, and there can be as many elif's as you want. Remember that for the value, if you want an 
        expression, it must be inside parenthesis. <!--TODO: More detail-->
    </p>
    <h4>Function Definitions</h4>
    <p>
        Function definitions define functions for later use in the program. The code in the function isn't executed until that
        function is called. It is expressed as:<br/>
        <code>{&#37; def ARG1 ... :: NAME1 VALUE1 ... &#37;}CODE{&#37; enddef &#37;}</code><br/>
        Arguments are defined only by their name, and any number of arguments are allowed. The <code>::</code> and everything
        after act like declaring variables in the Blocks.
    </p>
    <h4>Function Call</h4>
    <p>
        Calls a defined function. Expressed as:<br/>
        <code>{&#37; call FUNC PARAM1 ... &#37;}</code><br/>
        where FUNC is the name of the function and the parameters are values (number, variable, expression).
    </p>

</div>
{% endblock content %}

templates/score.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <div id="app">
        <h3>Scores</h3>
        {% csrf_token %}

        <div class="row">
            <strong>
                <div class="two columns">
                    <a @click="sortScores('rank_asc')">▲</a>
                    Rank
                    <a @click="sortScores('rank_des')">▼</a>
                </div>
                <div class="five columns">
                    <a @click="sortScores('name_asc')">▲</a>
                    Program
                    <a @click="sortScores('name_des')">▼</a>
                </div>
                <div class="one column">&nbsp;</div>
                <div class="two columns">
                    <a @click="sortScores('rank_asc')">▲</a>
                    Score
                    <a @click="sortScores('rank_des')">▼</a>
                </div>
                <div class="two columns">
                    <a @click="sortScores('points_asc')">▲</a>
                    Points
                    <a @click="sortScores('points_des')">▼</a>
                </div>
            </strong>
        </div>

        <program v-for="prog in hill_programs" v-bind:prog="prog"></program>

    </div>

    <script src="https://kit.fontawesome.com/130ffd39f1.js" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/vue"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="{% static 'js/score.js' %}"></script>
{% endblock content %}

templates/signup.html
{% extends "base.html" %}

{% block content %}
    <div id="app">
        <h2>{{ error }}</h2>

        <form action="{% url 'users:do_signup' %}" method="post" class="login-form">
            {% csrf_token %}

            <label for="username">Username: </label>
            <input type="text" id="username" name="username" required/>

            <br/>

            <label for="password">Password: </label>
            <input type="password" id="password" name="password" required/>

            <br/>

            <input type="submit" value="Sign Up" />
        </form>
    </div>
{% endblock content %}